In [2]:
import os
import pandas as pd

In [ ]:
# assign path
path, dirs, files = next(os.walk("./Datasets/"))
file_count = len(files)
# create empty list
dataframes_list = []

# append datasets to the list 
for i in range(file_count):
    print(f"./Datasets/{files[i]}")
    temp_df = pd.read_csv(f"./Datasets/{files[i]}")
    dataframes_list.append(temp_df)
    
# display datasets
for dataset in dataframes_list:
    display(dataset)

./Datasets/PointOfInterests.csv
./Datasets/PrivatePropertiesAmenities.csv
./Datasets/PropertySpatialMetricAssets.csv
./Datasets/SalesTransactions.csv
./Datasets/Subzones.csv

,Id,POI_Type,POI_Name,POI_InSubzone,POI_Latitude,POI_Longitude
0,1,MRT,Yio Chu Kang,228,1.381758,103.844801
1,2,MRT,Expo,213,1.334549,103.961546
2,3,MRT,Marymount,236,1.348777,103.839413
3,4,MRT,Botanic Gardens,164,1.322229,103.815469
4,5,MRT,Braddell,148,1.340444,103.846800
...,...,...,...,...,...,...
7790,11434,MRT,Choa Chu Kang,220,1.385366,103.744095
7791,11435,MRT,Bukit Gombak,255,1.358632,103.751814
7792,11436,MRT,Bukit Batok,175,1.349022,103.749540
7793,11437,MRT,Punggol,310,1.404544,103.902034
7794,11450,MRT,Unknown,999,NaN,NaN

,PropertyID,Gym,Pool,Playground,Tennis,Golf,Cafe,LapPool,KidsPool,Squash,Badminton,Basketball,BBQ,Jacuzzi,Security,Salon,Sauna,Shop
0,177968,0.0,1.0,1.0,1.0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
1,326704,1.0,1.0,1.0,0.0,0,0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0,1,0
2,363888,1.0,1.0,1.0,1.0,0,0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0,1,0
3,438256,0.0,0.0,1.0,0.0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,2576,1.0,1.0,1.0,1.0,1,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,115696,1.0,1.0,1.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0,0,0
2396,121184,1.0,1.0,1.0,1.0,1,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1,1
2397,176288,1.0,1.0,1.0,1.0,1,0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0,1,0
2398,181776,0.0,1.0,1.0,1.0,0,0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0,0,0
2399,363552,1.0,1.0,1.0,0.0,0,0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0,1,0

,PropertyID,NumberofSchoolsWithin500Mts,NumberOfMRTsWithin500Mts,NumberOfBusStopsWithin500Mts,TimeToRafflesByCarInSeconds,TimeToRafflesByPublicTransportInSeconds,TimeToAirportByCarInSeconds,TimeToAirportByPublicTransportInSeconds
0,112,2,1,12,775,1596,1063,4180
1,224,3,1,14,720,1745,1149,4329
2,336,0,1,11,580,1712,1186,5801
3,448,0,0,7,995,3746,1524,7390
4,560,0,0,9,751,2653,794,5177
...,...,...,...,...,...,...,...,...
19090,2312576,0,0,9,1332,3792,1541,7106
19091,2312688,8,1,7,582,1431,1311,5520
19092,2314032,0,0,6,1050,3425,1515,6706
19093,2318624,0,0,7,1090,3020,1637,7492
19094,2319184,1,0,12,931,2867,1396,5811

,Id,PropertyID,PropertyType,PropertyTenureType,PropertyNumberOfFloors,PropertynumberOfUnits,PropertyYearOfCompletion,PropertyInSubzone,PropertyLatitude,PropertyLongitude,FloorNoOfTransactedUnit,NumberOfBedroomsInTransactedUnit,TransactedPricePerSqFt,TransactionType,TransactionDate
0,1,202160,7,1,30.0,87.0,1993.0,69,1.296504,103.893393,10,NaN,2082.00,2,03/30/13
1,2,332080,7,2,NaN,1093.0,1986.0,92,1.310904,103.936393,16,NaN,1105.23,2,03/29/13
2,3,378896,2,2,NaN,397.0,2005.0,216,1.380404,103.935293,7,NaN,850.23,2,03/29/13
3,4,32256,1,1,NaN,42.0,2015.0,163,1.312304,103.883493,7,NaN,1319.10,0,03/28/13
4,5,375984,2,2,18.0,297.0,2004.0,217,1.385304,103.842093,5,NaN,929.63,2,03/28/13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517586,517584,228704,3,1,NaN,NaN,NaN,116,1.326204,103.796393,0,NaN,1988.34,2,05/24/12
517587,517585,228704,3,1,NaN,NaN,NaN,116,1.325904,103.797893,0,NaN,1765.23,2,05/28/12
517588,517586,288064,6,1,NaN,NaN,NaN,116,1.324104,103.796393,0,NaN,1935.48,2,6/7/2012
517589,517587,228704,3,1,NaN,NaN,NaN,116,1.324904,103.794393,0,NaN,1880.18,2,10/2/2014
517590,517588,228704,3,1,NaN,NaN,NaN,116,1.326204,103.798793,0,NaN,1793.36,2,12/17/15

,SubzoneId,SubzoneCode,SubzoneName,PlanningAreaId,PlanningAreaCode,PlanningAreaName
0,181,BSSZ03,Bishan East,1,BS,Bishan
1,186,BSSZ02,Marymount,1,BS,Bishan
2,236,BSSZ01,Upper Thomson,1,BS,Bishan
3,237,BKSZ02,Hong Kah North,2,BK,Bukit Batok
4,233,BKSZ05,Hillview,2,BK,Bukit Batok
...,...,...,...,...,...,...
318,120,RCSZ01,Farrer Park,53,RC,Rochor
319,15,SRSZ01,Robertson Quay,54,SR,Singapore River
320,3,SRSZ03,Boat Quay,54,SR,Singapore River
321,8,SRSZ02,Clarke Quay,54,SR,Singapore River
322,23,SVSZ01,Straits View,55,SV,Straits View

In [22]:
import functools as ft
# property_df = pd.DataFrame()
# property_df.join(dataframes_list[1:4], on='PropertyID')
property_df = ft.reduce(lambda left, right: pd.merge(left, right, on='PropertyID', how='outer'), dataframes_list[1:4])

In [25]:
property_df = pd.merge(property_df, dataframes_list[4], left_on='PropertyInSubzone', right_on='SubzoneId', how='left')

In [ ]:
property_df

In [26]:
POIsubzone_df = pd.merge(dataframes_list[0],dataframes_list[4],left_on='POI_InSubzone', right_on='SubzoneId', how='left')