In [1]:
import os
import pandas as pd

## “Which residential properties in Singapore provide the best value for money when considering price, accessibility, and nearby amenities?”

In [2]:
# assign path
path, dirs, files = next(os.walk("./Datasets/"))
file_count = len(files)
# create empty list
dataframes_list = []

# append datasets to the list 
for i in range(file_count):
    print(f"./Datasets/{files[i]}")
    temp_df = pd.read_csv(f"./Datasets/{files[i]}")
    dataframes_list.append(temp_df)
    
# display datasets
#for dataset in dataframes_list:
    #display(dataset)

./Datasets/PointOfInterests.csv
./Datasets/PrivatePropertiesAmenities.csv
./Datasets/PropertySpatialMetricAssets.csv
./Datasets/SalesTransactions.csv
./Datasets/Subzones.csv

In [3]:
dataframes_list[0].dropna(inplace=True)

In [4]:
dataframes_list[0]

,Id,POI_Type,POI_Name,POI_InSubzone,POI_Latitude,POI_Longitude
0,1,MRT,Yio Chu Kang,228,1.381758,103.844801
1,2,MRT,Expo,213,1.334549,103.961546
2,3,MRT,Marymount,236,1.348777,103.839413
3,4,MRT,Botanic Gardens,164,1.322229,103.815469
4,5,MRT,Braddell,148,1.340444,103.846800
...,...,...,...,...,...,...
7789,11433,MRT,Yew Tee,264,1.397519,103.747383
7790,11434,MRT,Choa Chu Kang,220,1.385366,103.744095
7791,11435,MRT,Bukit Gombak,255,1.358632,103.751814
7792,11436,MRT,Bukit Batok,175,1.349022,103.749540
7793,11437,MRT,Punggol,310,1.404544,103.902034

In [5]:
dataframes_list[1].drop_duplicates(inplace=True)
dataframes_list[1] = dataframes_list[1].fillna(0)
dataframes_list[1] = dataframes_list[1].replace("NIL", 0)
dataframes_list[1] = dataframes_list[1].astype(int)
dataframes_list[1]["Ameneties_Count"] = (dataframes_list[1].iloc[:, 1:] != 0).sum(axis=1)
dataframes_list[1]

,PropertyID,Gym,Pool,Playground,Tennis,Golf,Cafe,LapPool,KidsPool,Squash,Badminton,Basketball,BBQ,Jacuzzi,Security,Salon,Sauna,Shop,Ameneties_Count
0,177968,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,5
1,326704,1,1,1,0,0,0,1,1,0,0,0,1,1,1,0,1,0,9
2,363888,1,1,1,1,0,0,1,1,0,0,0,0,1,1,0,1,0,9
3,438256,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2
4,2576,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,115696,1,1,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,5
2396,121184,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,1,1,15
2397,176288,1,1,1,1,1,0,0,1,0,0,0,1,1,1,0,1,0,10
2398,181776,0,1,1,1,0,0,0,1,1,0,0,0,0,1,0,0,0,6
2399,363552,1,1,1,0,0,0,1,1,0,0,1,0,0,1,0,1,0,8

In [6]:
dataframes_list[2]

,PropertyID,NumberofSchoolsWithin500Mts,NumberOfMRTsWithin500Mts,NumberOfBusStopsWithin500Mts,TimeToRafflesByCarInSeconds,TimeToRafflesByPublicTransportInSeconds,TimeToAirportByCarInSeconds,TimeToAirportByPublicTransportInSeconds
0,112,2,1,12,775,1596,1063,4180
1,224,3,1,14,720,1745,1149,4329
2,336,0,1,11,580,1712,1186,5801
3,448,0,0,7,995,3746,1524,7390
4,560,0,0,9,751,2653,794,5177
...,...,...,...,...,...,...,...,...
19090,2312576,0,0,9,1332,3792,1541,7106
19091,2312688,8,1,7,582,1431,1311,5520
19092,2314032,0,0,6,1050,3425,1515,6706
19093,2318624,0,0,7,1090,3020,1637,7492
19094,2319184,1,0,12,931,2867,1396,5811

In [7]:
dataframes_list[3].drop_duplicates(inplace=True)
dataframes_list[3].drop(columns=["PropertyNumberOfFloors", "NumberOfBedroomsInTransactedUnit"], inplace=True)
dataframes_list[3] = dataframes_list[3].fillna("Unknown")

In [8]:
df = pd.merge(dataframes_list[3], dataframes_list[2], on="PropertyID", how="left")
df.dropna(inplace=True)
df

,Id,PropertyID,PropertyType,PropertyTenureType,PropertynumberOfUnits,PropertyYearOfCompletion,PropertyInSubzone,PropertyLatitude,PropertyLongitude,FloorNoOfTransactedUnit,TransactedPricePerSqFt,TransactionType,TransactionDate,NumberofSchoolsWithin500Mts,NumberOfMRTsWithin500Mts,NumberOfBusStopsWithin500Mts,TimeToRafflesByCarInSeconds,TimeToRafflesByPublicTransportInSeconds,TimeToAirportByCarInSeconds,TimeToAirportByPublicTransportInSeconds
0,1,202160,7,1,87.0,1993.0,69,1.296504,103.893393,10,2082.00,2,03/30/13,0.0,0.0,8.0,770.0,2729.0,765.0,5838.0
1,2,332080,7,2,1093.0,1986.0,92,1.310904,103.936393,16,1105.23,2,03/29/13,0.0,0.0,9.0,984.0,3705.0,588.0,4124.0
2,3,378896,2,2,397.0,2005.0,216,1.380404,103.935293,7,850.23,2,03/29/13,1.0,0.0,19.0,1310.0,4721.0,746.0,4941.0
3,4,32256,1,1,42.0,2015.0,163,1.312304,103.883493,7,1319.10,0,03/28/13,2.0,1.0,13.0,768.0,1652.0,1056.0,4236.0
4,5,375984,2,2,297.0,2004.0,217,1.385304,103.842093,5,929.63,2,03/28/13,0.0,1.0,16.0,1047.0,2640.0,1423.0,5954.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517583,517584,228704,3,1,Unknown,Unknown,116,1.326204,103.796393,0,1988.34,2,05/24/12,0.0,0.0,1.0,1075.0,3958.0,1604.0,7602.0
517584,517585,228704,3,1,Unknown,Unknown,116,1.325904,103.797893,0,1765.23,2,05/28/12,0.0,0.0,1.0,1075.0,3958.0,1604.0,7602.0
517585,517586,288064,6,1,Unknown,Unknown,116,1.324104,103.796393,0,1935.48,2,6/7/2012,0.0,0.0,0.0,1135.0,3517.0,1695.0,7979.0
517586,517587,228704,3,1,Unknown,Unknown,116,1.324904,103.794393,0,1880.18,2,10/2/2014,0.0,0.0,1.0,1075.0,3958.0,1604.0,7602.0
517587,517588,228704,3,1,Unknown,Unknown,116,1.326204,103.798793,0,1793.36,2,12/17/15,0.0,0.0,1.0,1075.0,3958.0,1604.0,7602.0

In [9]:
df = pd.merge(df, dataframes_list[1], on="PropertyID", how="left")
df.fillna(0, inplace=True)

,Id,PropertyID,PropertyType,PropertyTenureType,PropertynumberOfUnits,PropertyYearOfCompletion,PropertyInSubzone,PropertyLatitude,PropertyLongitude,FloorNoOfTransactedUnit,...,Squash,Badminton,Basketball,BBQ,Jacuzzi,Security,Salon,Sauna,Shop,Ameneties_Count
0,1,202160,7,1,87.0,1993.0,69,1.296504,103.893393,10,...,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,9.0
1,2,332080,7,2,1093.0,1986.0,92,1.310904,103.936393,16,...,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,10.0
2,3,378896,2,2,397.0,2005.0,216,1.380404,103.935293,7,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,15.0
3,4,32256,1,1,42.0,2015.0,163,1.312304,103.883493,7,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,15.0
4,5,375984,2,2,297.0,2004.0,217,1.385304,103.842093,5,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517253,517584,228704,3,1,Unknown,Unknown,116,1.326204,103.796393,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
517254,517585,228704,3,1,Unknown,Unknown,116,1.325904,103.797893,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
517255,517586,288064,6,1,Unknown,Unknown,116,1.324104,103.796393,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
517256,517587,228704,3,1,Unknown,Unknown,116,1.324904,103.794393,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
517257,517588,228704,3,1,Unknown,Unknown,116,1.326204,103.798793,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df['MRT_Score'] = (
    df['NumberOfMRTsWithin500Mts']
    - df['NumberOfMRTsWithin500Mts'].min()
) / (
    df['NumberOfMRTsWithin500Mts'].max()
    - df['NumberOfMRTsWithin500Mts'].min()
)
df['BusStop_Score'] = (
    df['NumberOfBusStopsWithin500Mts']
    - df['NumberOfBusStopsWithin500Mts'].min()
) / (
    df['NumberOfBusStopsWithin500Mts'].max()
    - df['NumberOfBusStopsWithin500Mts'].min()
)

In [11]:
df.to_csv("Cleaned Dataset.csv")

In [12]:
#property_df = pd.merge(property_df, dataframes_list[4], left_on='PropertyInSubzone', right_on='SubzoneId', how='left')

In [13]:
#property_df

In [14]:
#POIsubzone_df = pd.merge(dataframes_list[0],dataframes_list[4],left_on='POI_InSubzone', right_on='SubzoneId', how='left')